<?php
/**
 * Local full-text search via SQLite FTS5 or PostgreSQL tsvector.
 * Intentionally separate from Mastodon/cmplxdecay Elasticsearch on this host.
 *
 * Corpus: federated events (Create/Announce/Update), mentions, local masto_statuses.
 * Designed for 10^5–few×10^5 docs with incremental upserts (not a full reindex per query).
 */
declare(strict_types=1);
// Refuse direct HTTP hits (include/require only)
if (PHP_SAPI !== 'cli'
    && isset($_SERVER['SCRIPT_FILENAME'])
    && realpath((string) $_SERVER['SCRIPT_FILENAME']) === realpath(__FILE__)
) {
    http_response_code(403);
    header('Content-Type: text/plain; charset=utf-8');
    header('Cache-Control: no-store');
    echo 'Library only';
    exit;
}


/**
 * Create FTS docs table + external-content FTS5 index + sync triggers.
 */
function ap_search_fts_migrate(PDO $db): void
{
    if (ap_search_fts_driver($db) === 'pgsql') {
        $db->exec(<<<'SQL'
CREATE TABLE IF NOT EXISTS ap_search_docs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    source_pk BIGINT NOT NULL,
    object_id TEXT,
    created_at TEXT NOT NULL,
    body TEXT NOT NULL,
    UNIQUE(source, source_pk)
);
CREATE INDEX IF NOT EXISTS idx_ap_search_docs_object ON ap_search_docs(object_id);
CREATE INDEX IF NOT EXISTS idx_ap_search_docs_created ON ap_search_docs(created_at DESC);

CREATE TABLE IF NOT EXISTS ap_search_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

ALTER TABLE ap_search_docs
    ADD COLUMN IF NOT EXISTS body_tsv tsvector
    GENERATED ALWAYS AS (to_tsvector('simple', body)) STORED;
CREATE INDEX IF NOT EXISTS idx_ap_search_docs_body_tsv
    ON ap_search_docs USING GIN (body_tsv);
SQL);
        return;
    }

    $db->exec(<<<'SQL'
CREATE TABLE IF NOT EXISTS ap_search_docs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,
    source_pk INTEGER NOT NULL,
    object_id TEXT,
    created_at TEXT NOT NULL,
    body TEXT NOT NULL,
    UNIQUE(source, source_pk)
);
CREATE INDEX IF NOT EXISTS idx_ap_search_docs_object ON ap_search_docs(object_id);
CREATE INDEX IF NOT EXISTS idx_ap_search_docs_created ON ap_search_docs(created_at DESC);

CREATE TABLE IF NOT EXISTS ap_search_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
SQL);

    // FTS5 virtual table (external content = ap_search_docs.body)
    $hasFts = false;
    try {
        $st = $db->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='ap_search_fts'");
        $hasFts = (bool) $st->fetchColumn();
    } catch (Throwable $e) {
        $hasFts = false;
    }
    if (!$hasFts) {
        try {
            $db->exec(<<<'SQL'
CREATE VIRTUAL TABLE ap_search_fts USING fts5(
    body,
    content='ap_search_docs',
    content_rowid='id',
    tokenize='porter unicode61 remove_diacritics 2'
);
SQL);
        } catch (Throwable $e) {
            error_log('[ap-search-fts] CREATE fts5 failed (is FTS5 enabled?): ' . $e->getMessage());
            return;
        }
    }

    // Triggers keep FTS in sync with ap_search_docs
    $db->exec(<<<'SQL'
CREATE TRIGGER IF NOT EXISTS ap_search_docs_ai AFTER INSERT ON ap_search_docs BEGIN
  INSERT INTO ap_search_fts(rowid, body) VALUES (new.id, new.body);
END;
CREATE TRIGGER IF NOT EXISTS ap_search_docs_ad AFTER DELETE ON ap_search_docs BEGIN
  INSERT INTO ap_search_fts(ap_search_fts, rowid, body) VALUES('delete', old.id, old.body);
END;
CREATE TRIGGER IF NOT EXISTS ap_search_docs_au AFTER UPDATE OF body ON ap_search_docs BEGIN
  INSERT INTO ap_search_fts(ap_search_fts, rowid, body) VALUES('delete', old.id, old.body);
  INSERT INTO ap_search_fts(rowid, body) VALUES (new.id, new.body);
END;
SQL);
}

function ap_search_fts_driver(?PDO $db = null): string
{
    try {
        $driver = ($db ?? ap_db())->getAttribute(PDO::ATTR_DRIVER_NAME);
        return strtolower((string) $driver);
    } catch (Throwable $e) {
        return '';
    }
}

function ap_search_fts_available(): bool
{
    static $ok = null;
    if ($ok !== null) {
        return $ok;
    }
    try {
        if (ap_search_fts_driver() === 'pgsql') {
            $st = ap_db()->query("SELECT to_regclass('public.ap_search_docs') IS NOT NULL");
            $ok = (bool) $st->fetchColumn();
            return $ok;
        }
        $st = ap_db()->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='ap_search_fts'");
        $ok = (bool) $st->fetchColumn();
    } catch (Throwable $e) {
        $ok = false;
    }
    return $ok;
}

/** Translate the sanitized FTS5 query form to PostgreSQL tsquery syntax. */
function ap_search_fts_postgres_query(string $match): string
{
    $match = preg_replace('/([^\s]+)\*/u', '$1:*', $match) ?? $match;
    return str_replace([' AND ', ' OR '], [' & ', ' | '], $match);
}

function ap_search_fts_meta_get(string $key): ?string
{
    try {
        $st = ap_db()->prepare('SELECT value FROM ap_search_meta WHERE key = ?');
        $st->execute([$key]);
        $v = $st->fetchColumn();
        return $v === false ? null : (string) $v;
    } catch (Throwable $e) {
        return null;
    }
}

function ap_search_fts_meta_set(string $key, string $value): void
{
    try {
        ap_db()->prepare(
            'INSERT INTO ap_search_meta (key, value) VALUES (?, ?)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value'
        )->execute([$key, $value]);
    } catch (Throwable $e) {
        error_log('[ap-search-fts] meta_set: ' . $e->getMessage());
    }
}

/**
 * Normalize plaintext for indexing. Appends htag:token markers for reliable #tag MATCH.
 */
function ap_search_fts_normalize_body(string $plain, string $spoiler = ''): string
{
    $plain = trim(ap_fix_utf8($plain));
    $spoiler = trim(ap_fix_utf8($spoiler));
    $combined = $spoiler !== '' ? ($spoiler . "\n" . $plain) : $plain;
    $combined = html_entity_decode($combined, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $combined = preg_replace('/\s+/u', ' ', $combined) ?? $combined;
    $combined = mb_substr(trim($combined), 0, 8000);
    if ($combined === '') {
        return '';
    }
    $tags = [];
    if (preg_match_all('/#([\p{L}\p{N}_]{1,100})/u', $combined, $m)) {
        foreach ($m[1] as $t) {
            $norm = mb_strtolower($t);
            if ($norm !== '') {
                $tags[$norm] = true;
            }
        }
    }
    if ($tags) {
        // Use htag_NAME (not htag:NAME) — FTS5 treats colon as column syntax.
        $combined .= ' ' . implode(' ', array_map(static fn($t) => 'htag_' . $t, array_keys($tags)));
    }
    return $combined;
}

/**
 * Upsert one searchable document. No-op on empty body.
 *
 * @param 'event'|'mention'|'status' $source
 */
function ap_search_fts_upsert(string $source, int $sourcePk, ?string $objectId, string $createdAt, string $body): void
{
    if (!ap_search_fts_available() || $sourcePk <= 0) {
        return;
    }
    if (!in_array($source, ['event', 'mention', 'status'], true)) {
        return;
    }
    $body = trim($body);
    if ($body === '') {
        ap_search_fts_delete($source, $sourcePk);
        return;
    }
    $objectId = $objectId !== null && $objectId !== '' ? rtrim($objectId, '/') : null;
    $createdAt = $createdAt !== '' ? $createdAt : (function_exists('ap_db_now') ? ap_db_now() : gmdate('c'));
    try {
        ap_db()->prepare(
            'INSERT INTO ap_search_docs (source, source_pk, object_id, created_at, body)
             VALUES (?, ?, ?, ?, ?)
             ON CONFLICT(source, source_pk) DO UPDATE SET
               object_id = excluded.object_id,
               created_at = excluded.created_at,
               body = excluded.body'
        )->execute([$source, $sourcePk, $objectId, $createdAt, $body]);
    } catch (Throwable $e) {
        error_log('[ap-search-fts] upsert: ' . $e->getMessage());
    }
}

/** @param 'event'|'mention'|'status' $source */
function ap_search_fts_delete(string $source, int $sourcePk): void
{
    if (!ap_search_fts_available() || $sourcePk <= 0) {
        return;
    }
    try {
        ap_db()->prepare('DELETE FROM ap_search_docs WHERE source = ? AND source_pk = ?')
            ->execute([$source, $sourcePk]);
    } catch (Throwable $e) {
        error_log('[ap-search-fts] delete: ' . $e->getMessage());
    }
}

function ap_search_fts_delete_object(string $objectId): void
{
    if (!ap_search_fts_available()) {
        return;
    }
    $objectId = rtrim(trim($objectId), '/');
    if ($objectId === '' || !str_starts_with($objectId, 'https://')) {
        return;
    }
    try {
        ap_db()->prepare('DELETE FROM ap_search_docs WHERE object_id = ? OR object_id = ?')
            ->execute([$objectId, $objectId . '/']);
    } catch (Throwable $e) {
        error_log('[ap-search-fts] delete_object: ' . $e->getMessage());
    }
}

function ap_search_fts_index_event_row(array $row): void
{
    $id = (int) ($row['id'] ?? 0);
    if ($id <= 0) {
        return;
    }
    $type = strtolower((string) ($row['type'] ?? ''));
    $action = (string) ($row['action_taken'] ?? '');
    if (!in_array($type, ['create', 'announce', 'update', 'quote', 'quotepost'], true)) {
        ap_search_fts_delete('event', $id);
        return;
    }
    if (!in_array($action, ['log', 'local_observe', 'compose', 'local_fav_update'], true)) {
        ap_search_fts_delete('event', $id);
        return;
    }
    $plain = (string) ($row['summary'] ?? '');
    $spoiler = (string) ($row['spoiler_text'] ?? '');
    $body = ap_search_fts_normalize_body($plain, $spoiler);
    if ($body === '') {
        ap_search_fts_delete('event', $id);
        return;
    }
    ap_search_fts_upsert(
        'event',
        $id,
        isset($row['object_id']) ? (string) $row['object_id'] : null,
        (string) ($row['created_at'] ?? ''),
        $body
    );
}

function ap_search_fts_index_mention_row(array $row): void
{
    $id = (int) ($row['id'] ?? 0);
    if ($id <= 0) {
        return;
    }
    if (!empty($row['deleted_at'])) {
        ap_search_fts_delete('mention', $id);
        return;
    }
    // Skip synthetic account-bite placeholders
    $oid = (string) ($row['object_id'] ?? '');
    if (str_contains($oid, '/bites-received/')) {
        ap_search_fts_delete('mention', $id);
        return;
    }
    $act = strtolower((string) ($row['activity_type'] ?? $row['type'] ?? ''));
    if ($act === 'bite' && !str_contains($oid, '/notes/') && !str_contains($oid, '/statuses/')) {
        ap_search_fts_delete('mention', $id);
        return;
    }
    $body = ap_search_fts_normalize_body((string) ($row['content'] ?? ''), (string) ($row['spoiler_text'] ?? ''));
    if ($body === '') {
        ap_search_fts_delete('mention', $id);
        return;
    }
    ap_search_fts_upsert('mention', $id, $oid !== '' ? $oid : null, (string) ($row['created_at'] ?? ''), $body);
}

function ap_search_fts_index_status_row(array $row): void
{
    $id = (int) ($row['local_id'] ?? 0);
    if ($id <= 0) {
        return;
    }
    $body = ap_search_fts_normalize_body((string) ($row['content_text'] ?? ''), (string) ($row['spoiler_text'] ?? ''));
    if ($body === '') {
        ap_search_fts_delete('status', $id);
        return;
    }
    ap_search_fts_upsert(
        'status',
        $id,
        isset($row['note_id']) ? (string) $row['note_id'] : null,
        (string) ($row['published'] ?? ''),
        $body
    );
}

/**
 * Build a safe FTS5 MATCH query. Returns null if nothing searchable.
 */
function ap_search_fts_match_query(string $q, string $tagName = ''): ?string
{
    $q = trim(ap_fix_utf8($q));
    if ($tagName !== '') {
        $tag = mb_strtolower(preg_replace('/[^\p{L}\p{N}_]/u', '', $tagName) ?? '');
        if ($tag === '' || mb_strlen($tag) < 1) {
            return null;
        }
        // Prefer explicit hashtag token; also allow bare tag word
        return 'htag_' . $tag . ' OR ' . $tag;
    }
    if (mb_strlen($q) < 2) {
        return null;
    }
    // Strip FTS operators / quotes from user input; keep letters/numbers/_
    $q = str_replace(['"', "'", '*', '(', ')', ':', '^'], ' ', $q);
    $parts = preg_split('/\s+/u', mb_strtolower($q)) ?: [];
    $tokens = [];
    foreach ($parts as $p) {
        $p = preg_replace('/[^\p{L}\p{N}_]/u', '', $p) ?? '';
        if ($p === '' || mb_strlen($p) < 2) {
            continue;
        }
        // Prefix match helps partial words without scanning whole LIKE
        $tokens[] = $p . '*';
        if (count($tokens) >= 8) {
            break;
        }
    }
    if (!$tokens) {
        return null;
    }
    return implode(' AND ', $tokens);
}

/**
 * Search indexed docs. Returns newest-first rows with source + source_pk.
 *
 * @return list<array{source:string,source_pk:int,object_id:?string,created_at:string,rank:float}>
 */
function ap_search_fts_query(string $q, int $limit = 40, string $tagName = ''): array
{
    if (!ap_search_fts_available()) {
        return [];
    }
    ap_search_fts_maybe_backfill_slice();
    $match = ap_search_fts_match_query($q, $tagName);
    if ($match === null) {
        return [];
    }
    $limit = max(1, min(80, $limit));
    try {
        if (ap_search_fts_driver() === 'pgsql') {
            $tsquery = ap_search_fts_postgres_query($match);
            $st = ap_db()->prepare(
                "SELECT source, source_pk, object_id, created_at,
                        ts_rank_cd(body_tsv, to_tsquery('simple', ?)) AS rank
                 FROM ap_search_docs
                 WHERE body_tsv @@ to_tsquery('simple', ?)
                 ORDER BY rank DESC, created_at DESC
                 LIMIT ?"
            );
            $st->execute([$tsquery, $tsquery, $limit]);
        } else {
        // bm25: lower is better; order by rank then recency
            $st = ap_db()->prepare(
                "SELECT d.source, d.source_pk, d.object_id, d.created_at,
                        bm25(ap_search_fts) AS rank
                 FROM ap_search_fts
                 JOIN ap_search_docs d ON d.id = ap_search_fts.rowid
                 WHERE ap_search_fts MATCH ?
                 ORDER BY rank ASC, d.created_at DESC
                 LIMIT ?"
            );
            $st->execute([$match, $limit]);
        }
        $out = [];
        foreach ($st->fetchAll() ?: [] as $row) {
            $out[] = [
                'source' => (string) ($row['source'] ?? ''),
                'source_pk' => (int) ($row['source_pk'] ?? 0),
                'object_id' => isset($row['object_id']) ? (string) $row['object_id'] : null,
                'created_at' => (string) ($row['created_at'] ?? ''),
                'rank' => (float) ($row['rank'] ?? 0),
            ];
        }
        return $out;
    } catch (Throwable $e) {
        error_log('[ap-search-fts] query: ' . $e->getMessage());
        return [];
    }
}

/**
 * True if any doc matches (cheap existence / tag-seen).
 */
function ap_search_fts_exists(string $q, string $tagName = ''): bool
{
    if (!ap_search_fts_available()) {
        return false;
    }
    $match = ap_search_fts_match_query($q, $tagName);
    if ($match === null) {
        return false;
    }
    try {
        if (ap_search_fts_driver() === 'pgsql') {
            $st = ap_db()->prepare(
                "SELECT 1 FROM ap_search_docs
                 WHERE body_tsv @@ to_tsquery('simple', ?)
                 LIMIT 1"
            );
            $st->execute([ap_search_fts_postgres_query($match)]);
            return (bool) $st->fetchColumn();
        }
        $st = ap_db()->prepare('SELECT 1 FROM ap_search_fts WHERE ap_search_fts MATCH ? LIMIT 1');
        $st->execute([$match]);
        return (bool) $st->fetchColumn();
    } catch (Throwable $e) {
        return false;
    }
}

/**
 * Backfill a batch of rows. Safe to call repeatedly until done=true.
 *
 * @return array{done:bool,indexed:int,events:int,mentions:int,statuses:int}
 */
function ap_search_fts_backfill(int $batch = 2500): array
{
    $stats = ['done' => false, 'indexed' => 0, 'events' => 0, 'mentions' => 0, 'statuses' => 0];
    if (!ap_search_fts_available()) {
        $stats['done'] = true;
        return $stats;
    }
    $batch = max(100, min(10000, $batch));
    $db = ap_db();

    $eventCursor = (int) (ap_search_fts_meta_get('backfill_event_id') ?? '0');
    $mentionCursor = (int) (ap_search_fts_meta_get('backfill_mention_id') ?? '0');
    $statusCursor = (int) (ap_search_fts_meta_get('backfill_status_id') ?? '0');
    $phase = ap_search_fts_meta_get('backfill_phase') ?? 'events';

    try {
        if ($phase === 'events') {
            $st = $db->prepare(
                "SELECT * FROM events
                 WHERE id > ?
                   AND type IN ('Create', 'Announce', 'Update', 'Quote', 'QuotePost')
                   AND action_taken IN ('log', 'local_observe', 'compose', 'local_fav_update')
                   AND summary IS NOT NULL AND summary != ''
                 ORDER BY id ASC LIMIT ?"
            );
            $st->execute([$eventCursor, $batch]);
            $rows = $st->fetchAll() ?: [];
            foreach ($rows as $row) {
                ap_search_fts_index_event_row($row);
                $eventCursor = (int) $row['id'];
                $stats['events']++;
                $stats['indexed']++;
            }
            ap_search_fts_meta_set('backfill_event_id', (string) $eventCursor);
            if (count($rows) < $batch) {
                $phase = 'mentions';
                ap_search_fts_meta_set('backfill_phase', $phase);
            }
        }
        if ($phase === 'mentions') {
            $st = $db->prepare(
                'SELECT * FROM mentions
                 WHERE id > ? AND deleted_at IS NULL
                   AND content IS NOT NULL AND content != \'\'
                 ORDER BY id ASC LIMIT ?'
            );
            $st->execute([$mentionCursor, $batch]);
            $rows = $st->fetchAll() ?: [];
            foreach ($rows as $row) {
                ap_search_fts_index_mention_row($row);
                $mentionCursor = (int) $row['id'];
                $stats['mentions']++;
                $stats['indexed']++;
            }
            ap_search_fts_meta_set('backfill_mention_id', (string) $mentionCursor);
            if (count($rows) < $batch) {
                $phase = 'statuses';
                ap_search_fts_meta_set('backfill_phase', $phase);
            }
        }
        if ($phase === 'statuses') {
            $st = $db->prepare(
                'SELECT * FROM masto_statuses
                 WHERE local_id > ?
                 ORDER BY local_id ASC LIMIT ?'
            );
            $st->execute([$statusCursor, $batch]);
            $rows = $st->fetchAll() ?: [];
            foreach ($rows as $row) {
                ap_search_fts_index_status_row($row);
                $statusCursor = (int) $row['local_id'];
                $stats['statuses']++;
                $stats['indexed']++;
            }
            ap_search_fts_meta_set('backfill_status_id', (string) $statusCursor);
            if (count($rows) < $batch) {
                $phase = 'done';
                ap_search_fts_meta_set('backfill_phase', $phase);
                ap_search_fts_meta_set('backfill_done_at', function_exists('ap_db_now') ? ap_db_now() : gmdate('c'));
            }
        }
        $stats['done'] = ($phase === 'done');
    } catch (Throwable $e) {
        error_log('[ap-search-fts] backfill: ' . $e->getMessage());
    }
    return $stats;
}

/**
 * On-demand: if backfill incomplete, index one small slice (keeps first searches useful
 * without blocking a request on a full rebuild).
 */
function ap_search_fts_maybe_backfill_slice(): void
{
    if (!ap_search_fts_available()) {
        return;
    }
    if ((ap_search_fts_meta_get('backfill_phase') ?? '') === 'done') {
        return;
    }
    // Avoid stampedes: at most one slice per process every few seconds
    static $last = 0.0;
    $now = microtime(true);
    if ($now - $last < 2.0) {
        return;
    }
    $last = $now;
    ap_search_fts_backfill(800);
}

/**
 * Rebuild from scratch (admin/maintenance).
 *
 * @return array{done:bool,indexed:int}
 */
function ap_search_fts_rebuild(): array
{
    if (!ap_search_fts_available()) {
        return ['done' => true, 'indexed' => 0];
    }
    $db = ap_db();
    $db->exec('DELETE FROM ap_search_docs');
    if (ap_search_fts_driver($db) !== 'pgsql') {
        // Rebuild FTS from empty content table
        try {
            $db->exec("INSERT INTO ap_search_fts(ap_search_fts) VALUES('rebuild')");
        } catch (Throwable $e) {
            // ignore — triggers will repopulate on insert
        }
    }
    ap_search_fts_meta_set('backfill_phase', 'events');
    ap_search_fts_meta_set('backfill_event_id', '0');
    ap_search_fts_meta_set('backfill_mention_id', '0');
    ap_search_fts_meta_set('backfill_status_id', '0');
    $total = 0;
    for ($i = 0; $i < 200; $i++) {
        $s = ap_search_fts_backfill(3000);
        $total += (int) $s['indexed'];
        if (!empty($s['done'])) {
            return ['done' => true, 'indexed' => $total];
        }
    }
    return ['done' => false, 'indexed' => $total];
}
